version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --max_allowed_packet=256M
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    network_mode: host